spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      client:
        registration:
          okta:
            provider: okta
            client-id: LF34PketzgYXD2kOu1HvOOLBHwu9d2nY
            client-secret: _c2e81THku7KGG90WmHMNrYZklJkdnQlPah6NASLAgpwW0wbYX2cweL4EWL8GDNG
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8084/login/oauth2/code/okta
            scope:
              - openid
              - profile
              - email
              - offline_access
        provider:
          okta:
            issuer-uri: https://dev-x1izhrf6b8cbnfh5.okta.com/oauth2/default
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**,/staffs/**
            
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
